<a href="https://colab.research.google.com/github/vishnukm07/Data-Science-Lab/blob/main/Copy_of_Vishnu_K_Mohan_CO1_NumpyArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# program to create an array of all the even integers from 20 to 80
import numpy as np
x=np.arange(start=20,stop=80,step=2)
print(x)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [ ]:
#Write a program to create a numpy array and perform element-wise comparison (greater, greater_equal, less than, lesser_equal).
import numpy as np
x=np.array([2,5,15,17,24])
y=np.array([3,4,13,16,26])
print("a1:")
print(x)
print("a2:")
print(y)
print("a1>a2")
print(np.greater(x,y))
print("a1>=a2")
print(np.greater_equal(x,y))
print("a1<a2")
print(np.less(x,y))
print("a1<=a2")
print(np.less_equal(x,y))

a1:
[ 2  5 15 17 24]
a2:
[ 3  4 13 16 26]
a1>a2
[False  True  True  True False]
a1>=a2
[False  True  True  True False]
a1<a2
[ True False False False  True]
a1<=a2
[ True False False False  True]


In [ ]:
#program to multiply two given arrays of same size
import numpy as np
x=np.array([2,5,15,17,24])
y=np.array([3,4,13,16,26])
print("a1:")
print(x)
print("a2:")
print(y)
print(np.multiply(x,y))

a1:
[ 2  5 15 17 24]
a2:
[ 3  4 13 16 26]
[  6  20 195 272 624]


In [ ]:
#Program to save a given array to a text file and load it
import numpy as np
import os
x=np.arange(16).reshape(4,4)
print("array")
print(x)
h="cl1 cl2 cl3 cl4"
np.savetxt("myarray",x,fmt="%d",header=h)
print("From myarray Using loadtxt()")
print(np.loadtxt("myarray"))


array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
From myarray Using loadtxt()
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
